### ISSUE TITLE
rewrite README

### ISSUE THREAD

**Issue by orbeckst** [andywinhold/aworbits#2]
For your project I would change the README: visitors are not really interested in the "final project" aspect so delete all of that – perhaps just keep one sentence at the bottom saying that this originated as a final project in class [ASU PHY494: Computational Methods in Physics (spring 2016)](http://asu-compmethodsphysics-phy494.github.io/ASU-PHY494/). The README should tell people about the project itself, the authors, and the terms of the license.

**Comment by andywinhold** [comment]
@orbeckst Thank you for this. With how much everything is tracked on GitHub, it makes sense to have as much of it be clear and understandable as possible.
